do ->
  button = document.getElementById('cn-button')
  wrapper = document.getElementById('cn-wrapper')
  overlay = document.getElementById('cn-overlay')
  #open and close menu when the button is clicked
  open = false

  cnhandle = (e) ->
    e.stopPropagation()
    return

  handler = (e) ->
    `var e`
    if !e
      e = window.event
    e.stopPropagation()
    #so that it doesn't trigger click event on document
    if !open
      openNav()
    else
      closeNav()
    return

  openNav = ->
    open = true
    button.innerHTML = '-'
    classie.add overlay, 'on-overlay'
    classie.add wrapper, 'opened-nav'
    return

  closeNav = ->
    open = false
    button.innerHTML = '+'
    classie.remove overlay, 'on-overlay'
    classie.remove wrapper, 'opened-nav'
    return

  button.addEventListener 'click', handler, false
  wrapper.addEventListener 'click', cnhandle, false
  document.addEventListener 'click', closeNav
  return

# ---
# generated by js2coffee 2.2.0